[package]
name = "n2"
version = "0.1.0"
edition = "2018"
# std::thread::available_parallelism
rust-version = "1.59"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.10"
anyhow = "1.0"
libc = "0.2"
lazy_static = "1.4.0"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = { version = "0.3.6", features = [ "processenv", "consoleapi", "synchapi" ] }

[target.'cfg(not(any(windows, target_arch = "wasm32")))'.dependencies]
jemallocator = "0.5.0"

[dev-dependencies]
tempfile = "3.3.0"

[profile.release]
debug = true
lto = "fat"
codegen-units = 1
